#!/usr/bin/env node
// Build script: generates env-config.js from Netlify environment variables.
// Run automatically by Netlify's build step; env-config.js is gitignored.
// Supports both standard names and NEXT_PUBLIC_ variants (Supabase project exports).

const fs = require('fs');
const path = require('path');

const config = {
    // Accept NEXT_PUBLIC_ names (Supabase dashboard export format) as well as standard names
    SUPABASE_URL: process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY
        || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
        || ''
};

if (!config.SUPABASE_URL || !config.SUPABASE_ANON_KEY) {
    console.warn('[build-env] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY not set. The app will not connect to Supabase.');
}

const output = `// Auto-generated by build-env.js — do not commit\nwindow.__ENV__ = ${JSON.stringify(config, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'env-config.js'), output);
console.log('[build-env] Generated env-config.js with SUPABASE_URL:', config.SUPABASE_URL ? config.SUPABASE_URL.slice(0, 30) + '...' : '(not set)');
