#!/usr/bin/env node
// Build script: generates env-config.js from Netlify environment variables.
// Run automatically by Netlify's build step; env-config.js is gitignored.

const fs = require('fs');
const path = require('path');

const config = {
    SUPABASE_URL: process.env.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || ''
};

const output = `// Auto-generated by build-env.js — do not commit\nwindow.__ENV__ = ${JSON.stringify(config, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'env-config.js'), output);
console.log('[build-env] Generated env-config.js');
